### PR TITLE
Buddha vacana v2

### PR DESCRIPTION
**Pull request by sumbodhi**
Here's a quick demo..

Desktop:

Mobile:

### CODE REVIEW

**Comment by parthopdas** [comment]
i have merged it. please fix up the long BV issue with you next work item.

**Comment by sumbodhi** [comment]
long BV issue? what do you mean?

**Comment by parthopdas** [comment]
you mentioned it 
image

**Comment by sumbodhi** [comment]
it's fixed in this PR, it wasn't fixed in the original PR, so we're good

**Pull request merged**
